### ISSUE TITLE
关于 emoji 关键字的建议

### ISSUE THREAD

**Issue by S1ngS1ng** [rime-aca/OpenCC_Emoji#1]
麻烦问下，这里的 emoji 关键字来源是哪里呢？
要不要考虑下用 unicode 定义好的？或者把这些添加到现在的内容里？这里是链接：https://unicode.org/cldr/charts/dev/annotations/cjk.html

不过我感觉，有些关键字也不是那么常用。相比之下，搜狗拼音输入法的就稍微好些，macos 的有些也不错，但我都没找到源文件。

搜狗拼音里只能通过打开 emoji 输入窗口，hover 表情看到。

------

补充：
比如，之前搜狗输入法里，输入“不看” 就可以得到 🙈 。不知道从哪次更新开始，这样就打不出了= =

**Comment by LEOYoon-Tsaw** [comment]
哪有來源，關鍵字都是我自己想的，Unicode定義的那些有空我可以選一些加入。不過最好還是在實際中能夠讓人聯想到的詞才是好詞，繪文字的官方定義義意不大。
你如果有好的想法請直接提pull
